# Generated by Django 3.0.2 on 2020-02-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Calculate',
        ),
    ]
